scene.js
=> Fixed bug where metallic-roughness uniforms were immediately deleted.

shaders/pbr-vert.glsl
For https://github.com/KhronosGroup/glTF-WebGL-PBR/issues/41
=> Fix for normal computation in vertex shader

src/buffer.js, src/image.js, src/loader.js, src/main.js, src/renderer.js, src/utils.js, src/viewer.js
Users can now drop files directly into the viewer
* single glb files are supported
* gltf files are supported if all necessary files are dragged together
=> Drag and Drop

.vscode/settings.json, src/constants.js, src/drag_input.js, src/input.js, src/keyboard_input.js, src/main.js, src/mouse_input.js, src/touch_input.js, src/user_camera.js
• Panning with one finger
• Zooming with two fingers
=> Feature: touch input

electron/offscreen.js, headless.html, index.html, index_field.html, index_papermill.html, index_pisa.html, src/main.js, src/viewer.js
=> Feature: specify environmnt in headless

src/camera.js, src/renderer.js
=> Bugfix: gltf camera in transparent model

src/image_processor.js, src/math_utils.js, src/webgl.js
=> Bugfix: rectangular textures tiling

src/viewer.js
=> fixed scene rescaling after camera change

package.json, src/gltf_utils.js, src/viewer.js
=> Electron update #191

README.md
Hi, I think this correction is appropriate.
=> Fix a typo (specularContribution formula in Appendix)

README.md, src/shaders/metallic-roughness.frag
see https://github.com/KhronosGroup/glTF-Sample-Viewer/issues/210
=> Fixes issue 210

README.md, src/material.js, src/renderer.js, src/shaders/tonemapping.glsl, src/webgl.js
=> Added support of EXT_sRGB

src/environment.js, src/image.js, src/material.js, src/renderer.js, src/shaders/tonemapping.glsl, src/texture.js, src/webgl.js
WebGL 1.0, EXT_sRGB and mip map generating just does not work properly.
=> Switched back to non EXT_sRGB usage.

src/renderer.js, src/rendering_parameters.js, src/shaders/metallic-roughness.frag, src/shaders/tonemapping.glsl, src/user_interface.js
=> Renamed gammaCorrection to LINEARtoSRGB

package.json
=> fix offscreen rendering

src/material.js, src/shaders/pbr.frag, src/shaders/textures.glsl
Support for anisotropic intensity and direction textures.
=> Anisotropy textures

src/shaders/functions.glsl
=> invert TBN if surface is back-facing

README.md
Otherwise, new users might encounter issues like #271.
=> Remind users to install Git LFS.

README.md
There is now some info on how to start the web app locally in the readme
=> Update README.md with instructions for Web App

app_web/index.html, app_web/src/main.js, app_web/src/ui/sass.scss
fixes resolution for high dpi displays
fixes layout issues when setting a zoom factor
hide sidebar on mobile
=> Fix layout issues

source/GltfState/gltf_state.js, source/Renderer/renderer.js, source/Renderer/shaders/tonemapping.glsl
=> rename “3D Commerce” tonemapping to “Hill - Exposure Boost”

app_web/package.json, source/Renderer/webgl.js, source/gltf/material.js
=> Fix alpha mode error

API.md, source/GltfState/gltf_state.js, source/Renderer/renderer.js, source/Renderer/shaders/pbr.frag
For those channels:
- Base color
- Emissive
=> Add linear debug views

app_web/src/main.js, source/Renderer/renderer.js
- Transmission texture is not rendered when no transmissive material is present
- No frames are rendered at all when user gives no input (except for when animations are playing)
=> Performance fixes

source/Renderer/shaders/material_info.glsl
=> Fix ifdef in getNormalInfo

source/Renderer/shaders/pbr.frag
=> Add missing debug output for `KHR_materials_specular`

source/Renderer/shaders/pbr.frag
=> handle KHR_materials_unlit similar to regular shading

source/Renderer/shaders/iridescence.glsl, source/Renderer/shaders/material_info.glsl, source/Renderer/shaders/pbr.frag, source/gltf/material.js
See discussion: https://github.com/KhronosGroup/glTF/pull/2027
=> Change iridescenceIOR to iridescenceIor

source/Renderer/renderer.js
https://github.com/KhronosGroup/glTF-Sample-Viewer/issues/413
=> Consider current viewport aspect ratio for orthographic camera

source/gltf/skin.js
=> Accept missing inverse bind matrices

source/gltf/material.js
=> Fix sheen roughness sampler

source/gltf/accessor.js
=> Handle missing buffer view of accessor

source/Renderer/shaders/material_info.glsl
=> Avoid division by zero

source/Renderer/renderer.js, source/Renderer/webgl.js, source/ibl_sampler.js
Fixes #397 by properly testing for extension support.
=> Test for OES_texture_float_linear

app_web/index.html, app_web/src/logic/uimodel.js, app_web/src/ui/sass.scss
Camera rotation does not reset between orbit gestures.
=> Fix touch input

source/Renderer/webgl.js, source/gltf/accessor.js, source/gltf/animation_sampler.js
=> Fix morph stress test asset

source/Renderer/renderer.js, source/gltf/camera.js
=> Filter drawables behind camera each frame

source/Renderer/webgl.js
=> Avoid anisotropic filtering in combination with nearest filtering

rollup.config.js
=> Fix rollup config

source/Renderer/shaders/pbr.frag
=> Debug outputs for diffuse, specular, sheen, and clearcoat do not have ao applied

source/Renderer/shaders/material_info.glsl
https://github.com/KhronosGroup/glTF-Sample-Viewer/issues/465
=> Fix black artifacts caused by invalid tangents [465]

source/gltf/image.js
Fixes [473](https://github.com/KhronosGroup/glTF-Sample-Viewer/issues/473)
=> Fix loading of images with undefined mimetype [473]

.gitmodules
Change to https://github.com/KhronosGroup/glTF-Sample-Assets/
Fixes #472
=> Change assets subrepos url

package.json
=> Print warning when running npm run dev/build from root

source/Renderer/shaders/pbr.frag
=> Normalize thickness debug output using thickness factor

app_web/main.js, app_web/src/logic/uimodel.js, app_web/src/main.js, app_web/src/model_path_provider.js, app_web/src/ui/ui.js, source/ResourceLoader/loader.js, source/ResourceLoader/resource_loader.js, source/gltf/buffer.js, source/gltf/image.js
=> Fix loading images from subfolders when dropping files

source/gltf/primitive.js
https://github.com/KhronosGroup/glTF-Sample-Viewer/issues/496
=> Fix Accessor Deinterleaving for Tangent Generation [496]

source/GltfView/gltf_view.js
=> Correct vertex count for non-indexed prims

source/Renderer/renderer.js
=> Fix clear color

source/gltf/primitive.js
=> Fix broken joints attribute

source/gltf/accessor.js, source/gltf/gltf_utils.js
https://github.com/KhronosGroup/glTF-Sample-Viewer/issues/518
=> Fix calculation of bounding box [518]

app_web/src/main.js, source/gltf/gltf.js, source/gltf/image.js
=> Respect required extensions

source/gltf/primitive.js
https://github.com/KhronosGroup/glTF-Sample-Viewer/issues/521
=> Fix handedness of MikkTSpace tangent output [521]

app_web/index.html
=> Hide animation controls when no animations are available

source/libs/hdrpng.js
=> Add range check for hdr parsing

index.html, package.json, src/main.js, src/ui/ui.js
=> Validator: Add download button/Remove text area

index.html, src/main.js, src/ui/ui.js
Also adds more error handling for the validator in general
=> Add error message for disabled validator in chrome version 138
