main.js
scene.js

This makes the sRGB extension optional, and adds a fallback to RGBA.
Also it tweaks the mouse-wheel code to be more cross-browser compatible.
Together, these changes should allow this app to run correctly in the Firefox and Edge browsers.
Affects #1 and #3.

Tolerate lack of sRGB extension.

---

scene.js
shaders/pbr-frag.glsl

I happened to notice this today when reviewing this amazing repository with @emackey.  Roughness and metallic factor uniforms should always be defined in the pbr fragment shaders.  From the spec:
"If both factors and textures are present the factor value acts as a linear multiplier for the corresponding texture values."

Minor fix to adhere to spec for roughness and metallic factors.

---

scene.js
shaders/pbr-frag.glsl

I believe that there are parentheses missing in the denominator for the Cook-Torrance BRDF.  This would add a possible divide-by-zero error, so I padded the dot products a little. Does this seem correct to you?

Fix to denominator of Cook-Torrance brdf

---

main.js
scene.js
shaders/pbr-frag.glsl
shaders/pbr-vert.glsl

Rename the "normal matrix" to better reflect its usage as a transform from model -> world
Don't modify the gl context, instead store information about extensions in the state
move the camera/view calculations outside of the per-mesh loop
Add information about which papers the different lighting information came from to the shader.

Add attribution for the shader equations, also some misc cleanup

---

scene.js
shaders/pbr-frag.glsl

This PR wires up the uniforms for controlling occlusionStrength, normalScale, emissiveFactor, and baseColorFactor.  This fixes #13.
The shader implementation and defaults should match the recommendations in the spec.  I also found this glTF issue for additional background and guidance:
@KhronosGroup/glTF#885
CC @emackey @javagl

Added missing pbr factors.

---

scene.js

Fixes #27.
The "Triangle" model should be working again after this fix.

Make sure material exists before checking doubleSided flag.

---

main.js
scene.js
shaders/pbr-frag.glsl
shaders/pbr-vert.glsl

Fixed alternative calculation of k in geometricOcclusionSchlick (commented out) as discussed in PR #34 .  Superficial shader code cleanup for consistency (whitespace, uniform naming convention).

Minor shader cleanup

---

README.md
mesh.js
shaders/pbr-frag.glsl

Opening a PR for discussion on #44
Fairly hefty cleanup and reorganization attempt based on feedback in #44.
* Moved unused shading factor implementations out into the readme.  With PBRInputs struct, these can be easily swapped in for comparison
* Lots of code documentation, tracked down references mostly to the Epic Paper
* Renamed some core functions, with influence from @javagl's implementation
* Minor change/correction to calculation of `diffuseColor`.  Model lighting looks too dark and changed it to a more intuitive implemenation.  f0 is the reflection contribution at grazing angle, so the diffuse contribution is the inverse of that, and then adjusted by the inverse of the metallic.
* Switched the `geometricOcclusion` to use the `SmithG1` sub-function.  I also removed the additional …

PBR Fragment Shader Cleanup

---

main.js
mesh.js
scene.js
shaders/pbr-frag.glsl

Fix SRGB flag usage for platform where the extension is supported
Add manual shader sRGB decode for platforms where extension is not
supported
Gamma 2.2 encode the shader output

Color space correctness changes

---

README.md

The readme was showing incorrect mappings of which channels metallic and roughness pull from.  The shader is correct, but I want to minimize confusion.
The equation for diffuse coloring is also incorrect in the readme, as it should be multiplying light*color, not adding.

Update readme to show proper texture channels and diffuse color equation

---

style.css

Make text unselectable

---

README.md
shaders/pbr-frag.glsl

Hi all,
I just used this demo for a small recap of PBR basics, which worked nicely because it contains explanations in the README, it is able to visualize the impact of different parts of the BRDF, and the code is also pretty readable and has a lot of comments. So, it's pretty good for education :-)
However, I stumbled upon one thing that could possibly be documented explicitly, but it's not so far. Inside the fragment shader, the final lighting is computed as
```
vec3 color = NdotL * u_LightColor * (diffuseContrib + specContrib);
```
Especially when coming from a context where one has already implemented the Blinn-Phong model, this can look a bit confusing: Why does this equation not just sum up diffuse and specular parts of the "lighting"? And why do they not put just another `NdotL` …

Small Explanations on Intensity vs Reflectance

---

README.md

I've replaced the Renderman link with the most recent Wayback Machine link.
Closes issue: https://github.com/KhronosGroup/glTF-WebGL-PBR/issues/75

Updated Renderman link in README with the most recent Wayback Machine link

---

shaders/pbr-frag.glsl

Fixed a bug where `NdotV` can be `>1.0` resulting in a black spot if used with the diffuse term from "Disney implementation of diffuse from Physically-Based Shading at Disney" by Brent Burley.
```
vec3 diffuse(PBRInfo pbrInputs)
{
float f90 = 2.0 * pbrInputs.LdotH * pbrInputs.LdotH * pbrInputs.alphaRoughness - 0.5;
return (pbrInputs.diffuseColor / M_PI) * (1.0 + f90 * pow((1.0 - pbrInputs.NdotL), 5.0)) * (1.0 + f90 * pow((1.0 - pbrInputs.NdotV), 5.0));
}
```
The term `1.0-pbrInputs.NdotV` will become negative.

Fixed a bug where NdotV can be >1.0

---

shaders/pbr-frag.glsl

Without this the shader may fail compilation because the uniforms used in the getIBLContribution function are not being declared.

Wrap getIBLContribution with #ifdef USE_IBL

---

.gitattributes

Git had mistaken some of the smaller HDR files for text-based files, not binary.  This change to `.gitattributes` specifically marks all such image files as binary files, to protect them from end-of-line processing.
On Windows, `\n` in HDR files were being automatically converted to `\r\n`, which caused an infinite loop to appear here:
https://github.com/KhronosGroup/glTF-WebGL-PBR/blob/3186d988507d2bf94ff2940c2e2cf1b597a5d691/libs/hdrpng.js#L156
The corrupted files never matched the regex, and the entire browser hung.
NOTE for Windows users: After pulling this change, you may need to manually delete your `assets/images` folder, as it will still contain the old corrupted files.  Then use git commands to recreate the folder locally.  (I didn't have other pending changes, so I took the …

Windows EOL fix

---

package.json
rollup.config.js
src/renderer.js
src/shader_cache.js

As part of https://github.com/KhronosGroup/glTF-WebGL-PBR/issues/105, this bundles material shaders at build time so that end-users of the NPM package do not need to host the shaders themselves.

Inline shaders with compiled builds.

---

src/camera.js
src/renderer.js
src/scene.js

when sorting nodes by depth for transparency rendering, children may be drawn multiple times. 
This pull request fixes this issue and separates the gathering and sorting of nodes.

Node depth sort fix

---

README.md

Needs to be updated with DocToc manually if new sections are added.

Table of Contents for README

---

src/utils.js

Allow dots in filenames.

---

README.md

This makes use of the Khronos-hosted GitHub Pages version of the site.
Also, remove reference to fork of gltf-vscode.  Would be great to get those changes into a PR and merged into the published version of VSCode, but advertising a non-standard fork of the project is not the correct way to do that.

Update README.md links to Khronos deployment

---

.gitignore

This PR adds a `yarn.lock` entry to `.gitignore`. [Yarn](https://yarnpkg.com/en/) is a popular alternative dependency manager for NPM which automatically writes a `yarn.lock` file upon installing.
Kind regards,
Tim

Add Yarn lock file to .gitignore

---

src/renderer.js
src/rendering_parameters.js
src/shaders/tonemapping.glsl

This PR adds support for ACES tonemapping to the viewer.
Kind regards,
Tim

Add ACES tonemapping support

---

README.md

- The headless rendering example won't work without the submodule checkout having run, and while it's not rocket science to figure that out for yourself, it's still a stumbling block. Attention is a scarce resource these days; I know I always appreciate when the front page tutorial just works.
- The headless rendering is also such an interesting use case, I think it deserves to be its own full fledged heading.

Proposed README.md rearrangement

---

libs/ktx2image.js
src/image.js
src/webgl.js

https://ux3d.myjetbrains.com/youtrack/issue/SampleViewer-30

IBL: support 32-bit KTX files

---

.vscode/settings.json
src/material.js
src/shaders/brdf.glsl
src/shaders/pbr.frag

This moves the calculation for `f0_ior` out of the fragment shader and up to the app level.
Also, glTF 1.0 assets are excluded from search results, because searching for GLSL code was hitting too many false positives there.

Move f0_ior to an app-level computation.

---

src/shaders/functions.glsl

When `HAS_VERTEX_COLOR_VEC3` is defined, the vertex shader produces a type error as `v_Color` is a `vec4` trying to be assigned to `color.rgb` which is a `vec3`.
I suspect this feature is not used often enough that it just slipped between the cracks.

Fixes type error for vec3 vertex color inside vertex shader.

---

src/gltf_utils.js
src/interpolator.js
src/renderer.js
src/rendering_parameters.js
src/shaders/pbr.frag
src/shaders/punctual.glsl
src/user_camera.js
src/viewer.js

Fix the following bugs
- Correct Application of Ambient Occlusion Map: fix https://github.com/KhronosGroup/glTF-Sample-Viewer/issues/138
- Correct DEBUG_NORMAL output: fix https://github.com/KhronosGroup/glTF-Sample-Viewer/issues/265
- Calculate animation sample STEP correctly: fix https://github.com/KhronosGroup/glTF-Sample-Viewer/issues/269
- Correct brightness of KHR_lights_punctual lights: fix https://github.com/KhronosGroup/glTF-Sample-Viewer/issues/275
Also fixes a bug where front facing normals were falsely interpreted as back facing and flipped even if the material was not double sided.

Sample Viewer Enhancements: Fix bugs 

---

README.md
app_web/README.md
source/Renderer/shaders/pbr.frag

UX3D is still prominently listed in the README's credits with a link to the main UX3D site as the primary developer.
Almost all other references to the UX3D intermediate development version have been updated to final Khronos links.

Update various links to official sources.

---

app_web/src/main.js

1. drag and drop  [Avocado.zip](https://github.com/KhronosGroup/glTF-Sample-Viewer/files/6319257/Avocado.zip) into glTF viewer
2. drag and drop  [Avocado.zip](https://github.com/KhronosGroup/glTF-Sample-Viewer/files/6319257/Avocado.zip) into glTF viewer a second time
--> error message appears

reload ktx lib as a workaround for an error from ktx lib

---

source/gltf/camera.js

This fixes a bug where in some cases the transform of a gltf node was not correctly applied to the camera.

Use node transform directly

---

source/gltf/material.js

If an empty material is defined, use metallic roughness default values

Fix empty material

---

source/Renderer/shaders/pbr.frag

Is transmissionFactor double counting?
[ `vec3 diffuse = mix(f_diffuse, f_transmission, materialInfo.transmissionFactor);`](https://github.com/KhronosGroup/glTF-Sample-Viewer/blob/master/source/Renderer/shaders/pbr.frag#L267)

correct transmissionFactor double counting

---

source/Renderer/renderer.js
source/gltf/light.js

Properly render punctual lights which are instantiated by more than one node.
Fixes #401

Lights can be instantiated by multiple nodes

---

source/Renderer/renderer.js

Fixes punctual lights which are located deeper in the node hierarchy.

Gather all lights recursively in `getVisibleLights()`

---

source/Renderer/renderer.js

Sort if transparent drawables are present

---

source/Renderer/shaders/pbr.frag

All non-color debug channels output in linear color space

---

app_web/index.html
app_web/src/logic/uimodel.js
app_web/src/ui/sass.scss
app_web/src/ui/ui.js

This is based on a comment by @javagl during the Tooling TSG meeting earlier today.  It was pointed out that the Sample Viewer doesn't display a credit line for models that are marked CC-BY or similar.
I've renamed the "XMP" tab to "Credits" and included `asset.copyright` and `asset.generator` above the existing XMP data (if any) on the tab.  I also placed a copy of `asset.copyright` alone at the bottom of the "Model" tab, for visibility.
Unfortunately this has highlighted that a great many sample models are completely missing `asset.copyright` information, particularly ones marked CC-BY that need to be carrying that information.  However, many models contributed by myself and @echadwick-wayfair do indeed include the correct license in the `asset.copyright` field, for example …

Add model "copyright" and "generator" tags to credits panel

---

source/Renderer/shaders/punctual.glsl

in spot lights, rather than smoothstep

use spec. for ang. attenuation

---

.eslintrc.json
app_web/package.json
app_web/rollup.config.js
app_web/src/model_path_provider.js
package.json
rollup.config.js
source/ResourceLoader/resource_loader.js
source/gltf/buffer.js
source/package.json

Replaces the calls to the Axios package by the built-in fetch API. This also resolves [this security issue](https://github.com/KhronosGroup/glTF-Sample-Viewer/security/dependabot/7).

Replace `axios` by `fetch`

---

API.md
app_headless/index.js
app_web/src/logic/uimodel.js
app_web/src/main.js
app_web/src/ui/ui.js
package.json
source/GltfState/gltf_state.js
source/Renderer/renderer.js
source/Renderer/shaders/tonemapping.glsl

Based on a presentation that @elalish gave to PBR TSG today, along with his corresponding [tone mapping blog post](https://modelviewer.dev/examples/tone-mapping), here is an implementation of the new tone mapper.  This PR does a few things:
- Adds the new Khronos PBR Neutral tone mapper, and sets it as default
- Changes the default lighting from `footprint_court` to `Cannon_Exterior`, for more natural colors and better contrast
- Regenerates `API.md` picking up some fixes from a prior PR (sorry @abwood I forgot API.md was autogenerated)
- Fixes assorted warnings from ESLint

Khronos "PBR Neutral" tone mapping

---

API.md
source/GltfState/gltf_state.js
source/Renderer/shaders/tonemapping.glsl

Updated the "Khronos PBR Neutral" tone mapper with a small mathematical tweak that was published to its new location:
https://github.com/KhronosGroup/ToneMapping/blob/main/PBR_Neutral/pbrNeutral.glsl
I recall this change was desired to make the tone mapper mathematically invertible.  Also some trailing whitespace was removed.
/cc @elalish

Update "PBR Neutral" tone mapping with recent change.

---

source/Renderer/shaders/pbr.frag

Fixes #507
Debug views of extensions with one factor property now display this factor correctly.
For metallic roughness and specular other extensions on the same material can have an effect on their debug view. Separating this in the shader would be difficult.
One could add a feature in the future to automatically disable all other material extensions if a debug view of an extension is selected. Currently this can be done manually via the UI.

Include factors in main extension debug channels

---

source/Renderer/shaders/punctual.glsl

The math can be simplified per @lexaknyazev's refactoring in https://github.com/KhronosGroup/glTF/issues/2390#issuecomment-2158480643.
This avoids a situation where the attenuationColor might have some or all zeros in it, causing a `log(0)` error in the shader.
I've successfully tested this with sample assets AttenuationTest, DragonAttenuation, and the custom test from the above-linked issue.

Refactor attenuation math to avoid -log(0.0)

---

src/main.js

Prevent stopping user interface when broken glTF was loaded and clear with empty glTF instead.
https://github.com/KhronosGroup/glTF-Sample-Viewer/issues/574

Catch error during gltf loading and clear with empty gltf [574]

---

index.html
src/ui/sass.scss

This is needed if the height is too small (e.g. landscape mode or used as an iframe)

Add scrollbar to tabs

---

src/ui/sass.scss
src/ui/ui.js

Mobile browser can overlap the page with their own ui elements. These do not reduce the vh property used in css. This can be mitigated using the dvh (dynamic view height) property instead.
fixes KhronosGroup/glTF-Sample-Viewer#593
(Additionally this pr replaces window.innerWidth with documen.documentElement.clientWidth for mobile detection, since the former does not report the actual window width on ios. [mozilla innerWidth](https://developer.mozilla.org/en-US/docs/Web/API/Window/innerWidth) [webkit bug](https://bugs.webkit.org/show_bug.cgi?id=174362) )

Fix UI cutoff on mobile

---

src/ui/ui.js

Fixes #599
The error from this issue is caused by a firefox bug in injected code for form autocompletion.
With this fix this error (and all errors without script URL) is not shown via our error toast.

Do not show toast for injected code (URL does not exist)
